/**
 * 炼金配方配置
 */

export interface AlchemyRecipe {
  recipeIndex: number;
  inputs: Record<string, { count: number }>;
  description?: string;
}

export interface AlchemyItem {
  id: string;
  name: string;
  recipes: AlchemyRecipe[];
  category: 'essence' | 'potion';
}

export const ALCHEMY_RECIPES: AlchemyItem[] = [
  // 战力精华系列
  {
    id: 'pure_monster_essence_lv1',
    name: '战力精华Lv1',
    recipes: [{ recipeIndex: 0, inputs: { '(monster_essence_lv1)': { count: 32 }, mysticalEssence: { count: 5 } } }],
    category: 'essence',
  },
  {
    id: 'pure_monster_essence_lv2',
    name: '战力精华Lv2',
    recipes: [{ recipeIndex: 0, inputs: { '(monster_essence_lv2)': { count: 24 }, mysticalEssence: { count: 5 } } }],
    category: 'essence',
  },
  {
    id: 'pure_monster_essence_lv3',
    name: '战力精华Lv3',
    recipes: [{ recipeIndex: 0, inputs: { '(monster_essence_lv3)': { count: 12 }, mysticalEssence: { count: 5 } } }],
    category: 'essence',
  },
  {
    id: 'pure_monster_essence_lv4',
    name: '战力精华Lv4',
    recipes: [{ recipeIndex: 0, inputs: { '(monster_essence_lv4)': { count: 4 }, mysticalEssence: { count: 5 } } }],
    category: 'essence',
  },
  // 专精精华系列
  {
    id: 'sewingEssence',
    name: '织物精华',
    recipes: [
      { recipeIndex: 0, inputs: { catHairball: { count: 10 }, wool: { count: 33 } }, description: '猫毛球+羊毛' },
      { recipeIndex: 1, inputs: { catHairball: { count: 10 }, cashmere: { count: 1 } }, description: '猫毛球+羊绒' },
      { recipeIndex: 2, inputs: { catHairball: { count: 10 }, silk: { count: 33 } }, description: '猫毛球+蚕丝' },
      { recipeIndex: 3, inputs: { catHairball: { count: 10 }, silkFabric: { count: 1 } }, description: '猫毛球+丝绸' },
      { recipeIndex: 4, inputs: { catHairball: { count: 10 }, fluff: { count: 12 } }, description: '猫毛球+绒毛' },
      { recipeIndex: 5, inputs: { catHairball: { count: 10 }, fluffFabric: { count: 1 } }, description: '猫毛球+绒布' },
    ],
    category: 'essence',
  },
  {
    id: 'knowledgeEssence',
    name: '知识精华',
    recipes: [
      {
        recipeIndex: 0,
        inputs: { '(lv1SkillBook)': { count: 150 }, magicScroll: { count: 1 } },
        description: 'Lv1技能书',
      },
      {
        recipeIndex: 1,
        inputs: { '(lv2SkillBook)': { count: 75 }, magicScroll: { count: 1 } },
        description: 'Lv2技能书',
      },
      {
        recipeIndex: 2,
        inputs: { '(lv3SkillBook)': { count: 50 }, magicScroll: { count: 1 } },
        description: 'Lv3技能书',
      },
      {
        recipeIndex: 3,
        inputs: { '(lv4SkillBook)': { count: 25 }, magicScroll: { count: 1 } },
        description: 'Lv4技能书',
      },
    ],
    category: 'essence',
  },
  {
    id: 'nutrientEssence',
    name: '营养精华',
    recipes: [
      { recipeIndex: 0, inputs: { '(lv1Food)': { count: 100 } }, description: 'Lv1食物' },
      { recipeIndex: 1, inputs: { '(lv2Food)': { count: 50 } }, description: 'Lv2食物' },
      { recipeIndex: 2, inputs: { '(lv3Food)': { count: 25 } }, description: 'Lv3食物' },
      { recipeIndex: 3, inputs: { '(lv4Food)': { count: 10 } }, description: 'Lv4食物' },
    ],
    category: 'essence',
  },
  {
    id: 'craftingEssence',
    name: '矿物精华',
    recipes: [
      { recipeIndex: 0, inputs: { iron: { count: 10 }, steel: { count: 10 } }, description: '铁+钢' },
      { recipeIndex: 1, inputs: { iron: { count: 10 }, silverOre: { count: 33 } }, description: '铁+银矿' },
      { recipeIndex: 2, inputs: { iron: { count: 10 }, silverIngot: { count: 10 } }, description: '铁+银锭' },
      { recipeIndex: 3, inputs: { iron: { count: 10 }, mithrilOre: { count: 33 } }, description: '铁+秘银矿' },
      { recipeIndex: 4, inputs: { iron: { count: 10 }, mithrilIngot: { count: 10 } }, description: '铁+秘银锭' },
      { recipeIndex: 5, inputs: { iron: { count: 10 }, fishscaleMineral: { count: 35 } }, description: '铁+鱼鳞矿' },
      {
        recipeIndex: 6,
        inputs: { iron: { count: 10 }, fishscaleMineralIgnot: { count: 6 } },
        description: '铁+鱼鳞锭',
      },
      { recipeIndex: 7, inputs: { iron: { count: 10 }, shadowSteel: { count: 4 } }, description: '铁+暗影钢' },
    ],
    category: 'essence',
  },
  // 药水系列
  {
    id: 'manaPotion',
    name: '魔力药水',
    recipes: [
      { recipeIndex: 0, inputs: { berry: { count: 10 }, honey: { count: 1 }, '(glass,container)': { count: 1 } } },
    ],
    category: 'potion',
  },
  {
    id: 'monoPolarElixir',
    name: '单极药剂',
    recipes: [
      {
        recipeIndex: 0,
        inputs: {
          slimeGel: { count: 5 },
          slimeCore: { count: 3 },
          honey: { count: 2 },
          '(glass,container)': { count: 1 },
        },
        description: '史莱姆凝胶+蜂蜜',
      },
      {
        recipeIndex: 1,
        inputs: {
          '(slime)': { count: 5 },
          slimeCore: { count: 3 },
          '(liquid)': { count: 2 },
          '(glass,container)': { count: 1 },
        },
        description: '史莱姆+液体',
      },
    ],
    category: 'potion',
  },
  {
    id: 'magicalMonoPolarElixir',
    name: '魔法单极药剂',
    recipes: [
      {
        recipeIndex: 0,
        inputs: { magicalElixir: { count: 1 }, '(slime)': { count: 1 }, monoPolarElixir: { count: 1 } },
      },
    ],
    category: 'potion',
  },
];

export const ESSENCE_LEVEL_MAP: Record<string, number> = {
  pure_monster_essence_lv1: 1,
  pure_monster_essence_lv2: 2,
  pure_monster_essence_lv3: 3,
  pure_monster_essence_lv4: 4,
};

// 特殊标签对应的资源映射
export const TAG_RESOURCE_MAP: Record<string, string[]> = {
  '(glass,container)': ['glassBottles'],
  '(slime)': ['slimeGel', 'iceGel'],
  '(liquid)': [
    'honey',
    'amberSap',
    'milk',
    'fishSoup',
    'mushroomStew',
    'berryWine',
    'dawnBlossomWine',
    'windBellWine',
    'battleKnowledgeCocktail',
    'milkManaShake',
    'windBellMilkShake',
    'grapeMilkManaShake',
    'grapeWindBellMilkShake',
    'healingPotion',
    'manaPotion',
    'hasteElixir',
    'monoPolarElixir',
    'healingPotion_2',
    'swiftElixir',
    'magicalElixir',
    'cognitionStrikeElixir',
    'swiftMonoPolarElixir',
    'magicalMonoPolarElixir',
    'breezeElixir',
    'slimeGel',
    'iceGel',
  ],
  '(lv1SkillBook)': [
    'boneShieldSkillBook',
    'baseHealSkillBook',
    'poisonSkillBook',
    'doubleStrikeSkillBook',
    'freezeSkillBook',
    'iceBombSkillBook',
    'ironWallSkillBook',
    'curseSkillBook',
    'bindSkillBook',
    'confuseSkillBook',
  ],
  '(lv2SkillBook)': [
    'corrosiveBreathSkillBook',
    'summonBerryBirdSkillBook',
    'selfHealSkillBook',
    'sweepSkillBook',
    'baseGroupHealSkillBook',
    'powerStrikeSkillBook',
    'lowestHpStrikeSkillBook',
    'explosiveShotSkillBook',
    'lifeDrainSkillBook',
    'roarSkillBook',
    'groupCurseSkillBook',
    'holyLightSkillBook',
    'blessSkillBook',
    'groupRegenSkillBook',
    'astralBarrierSkillBook',
    'astralBlastSkillBook',
    'selfRepairSkillBook',
    'cleanseSkillBook',
    'cometStrikeSkillBook',
    'armorBreakSkillBook',
    'starTrapSkillBook',
    'ambushSkillBook',
    'poisonClawSkillBook',
    'shadowStepSkillBook',
    'silenceStrikeSkillBook',
    'slientSmokeScreenSkillBook',
    'stardustMouseSwapSkillBook',
    'dizzySpinSkillBook',
    'carouselOverdriveSkillBook',
    'candyBombSkillBook',
    'prankSmokeSkillBook',
    'starlightSanctuarySkillBook',
    'sealMagicSkillBook',
    'banishSkillBook',
  ],
  '(lv3SkillBook)': [
    'groupShieldSkillBook',
    'guardianLaserSkillBook',
    'lavaBreathSkillBook',
    'dragonRoarSkillBook',
    'blizzardSkillBook',
    'shadowBurstSkillBook',
    'reviveSkillBook',
    'groupSilenceSkillBook',
    'astralStormSkillBook',
    'mirrorImageSkillBook',
    'shadowAssassinUltSkillBook',
    'mercenaryTauntSkillBook',
    'plushTauntSkillBook',
    'ghostlyStrikeSkillBook',
    'paradeHornSkillBook',
    'clownSummonSkillBook',
    'kingAegisSkillBook',
    'detectMagicSkillBook',
    'punishSkillBook',
    'forbiddenMagicSkillBook',
  ],
  '(lv4SkillBook)': [
    'threadingNeedleSkillBook',
    'natureGiftSkillBook',
    'knowledgeInspirationSkillBook',
    'sowMelonsReapMelonsSkillBook',
    'enhanceEmpowerSkillBook',
    'enhanceStrikeSkillBook',
    'fishmanSkillSkillBook',
    'forgeSkillCraftTurretSkillBook',
    'forgeSkillCraftMeowColossusSkillBook',
    'chefSkillSkillBook',
    'beastpackRoarSkillBook',
  ],
  '(lv1Food)': ['mushroom', 'berry', 'honey', 'fish'],
  '(lv2Food)': [
    'simpleSalad',
    'wildFruitMix',
    'fishSoup',
    'berryPie',
    'mushroomStew',
    'catMint',
    'catSnack',
    'ryeBread',
    'ryeEnergyBar',
  ],
  '(lv3Food)': [
    'luxuryCatFood',
    'sashimiPlatter',
    'custardPudding',
    'luckyMint',
    'luckySashimiPlatter',
    'ryeEggPancake',
    'moltenRyeEggTart',
    'cloudFluffCandy',
    'milkManaShake',
    'windBellMilkShake',
    'grapeMilkManaShake',
    'grapeWindBellMilkShake',
    'cannedTuna',
    'cannedShrimp',
    'cannedRainbowFish',
    'cannedMysticalKoi',
    'collectingTart',
    'fishingTart',
    'miningTart',
    'manufactureAndForgingTart',
    'collectingTartLv2',
    'fishingTartLv2',
    'miningTartLv2',
    'manufactureAndForgingTartLv2',
  ],
  '(lv4Food)': [
    'superLuckyBerryPie',
    'superLuckyMushroomStew',
    'cannedCrystalCarpTuna',
    'cannedCrystalCarpShrimp',
    'cannedCrystalCarpRainbowFish',
    'cannedCrystalCarpMysticalKoi',
    'farmingAnimalTart',
    'sewingTart',
    'cookingTart',
    'knowledgeTart',
    'exploreTart',
    'farmingAnimalTartLv2',
    'sewingTartLv2',
    'cookingTartLv2',
    'knowledgeTartLv2',
    'exploreTartLv2',
  ],
  '(monster_essence_lv1)': [
    'slimeGel',
    'slimeCore',
    'goblinEar',
    'goblinDagger',
    'batWing',
    'batTooth',
    'wolfFang',
    'wolfPelt',
    'skeletonBone',
    'skeletonShield',
    'lizardScale',
    'lizardTail',
    'trollHide',
    'scorpionStinger',
    'scorpionCarapace',
    'iceGel',
    'snowWolfFur',
    'iceBomb',
    'iceBatWing',
    'snowRabbitFur',
    'shadowFur',
    'ironPawArmor',
    'phantomWhisker',
    'toxicFur',
    'smokeBall',
  ],
  '(monster_essence_lv2)': [
    'toxicSpore',
    'mushroomCap',
    'spiritEssence',
    'ectoplasm',
    'trollClub',
    'guardianCore',
    'ancientGear',
    'frostCrystal',
    'frostDagger',
    'frostEssence',
    'snowBeastHide',
    'catShadowGem',
    'golemCore',
    'witchHat',
    'abyssalCloak',
    'starEssence',
    'starShard',
    'trapParts',
    'starDust',
    'nightEyeGem',
    'whiskerCharm',
    'shadowCape',
    'candyBomb',
    'plushFur',
    'sealBell',
    'tomeFragment',
    'memoryPage',
    'rusted_chain_link',
    'soul_energy_shard',
    'dark_sigil_fragment',
    'faded_remnant',
    'loose_gear_piece',
  ],
  '(monster_essence_lv3)': [
    'lavaHeart',
    'dragonScale',
    'snowBeastFang',
    'curseWing',
    'shadowOrb',
    'starRelic',
    'rareClaw',
    'ghostEssence',
    'owlFeather',
    'darkCrystal',
    'royal_claw_fragment',
    'phantom_minor_core',
    'br1_onyx_shield_shard',
    'wd1_wardens_verdict',
    'wd1_oathbound_link',
    'ma1_tremor_fur',
    'ec1_echoing_stone',
    'ec1_resonance_lattice',
    'rg1_riftclaw_talon',
    'sw1_hushwoven_thread',
    'nb1_duskshade_whisker',
    'nb1_shadow_pounce_band',
    'ha1_hexstring_bowstring',
    'ha1_binding_arrowhead',
    'vc1_void_ichor',
    'mk1_mirror_etched_shard',
    'mk1_inverted_step_lace',
    'qn_chorus_veil',
    'hb_faceless_membrane',
    'hb_paradox_core',
    'oc_xuansteel_slab',
  ],
  '(monster_essence_lv4)': [
    'frostCrown',
    'ancestorCrown',
    'starCrown',
    'paradeCape',
    'empressCloak',
    'loadOfamusementPark',
    'knowledgeCrown',
    'libraryKingBadge',
    'domination_seal',
    'overloadCrown',
    'qn_echo_diadem',
    'kg_nocturne_scepter_grip',
    'kg_obsidian_crown_shard',
    'hb_null_signature',
    'oc_fortress_heart',
  ],
};
